Feat: while statement
miningape/pychart pull request #57
Opened 2022-03-20 14:10 UTC by GangstersPairOfDice

Added support for while statement using previously implemented syntax, new token, etc.

Usage in main.pych:
while ( expression ) { print("jeff"); }

Currently acts as a function when the expression is false, where it will just run through once.

Also breaks the entire program if an unknown variable is entered in the expression. = )

2022-03-20 14:12 UTC, miningape commented on src/pychart/__init__.py
> +__version__ = '0.6.9'
Classy

2022-03-20 14:13 UTC, miningape commented on src/pychart/_interpreter/pyparser.py
> +        # thassa bout it
Maybe move it somewhere else lol

2022-03-20 14:14 UTC, miningape approved these changes
LGTM

2022-03-20 14:14 UTC, miningape commented on src/pychart/_interpreter/statement.py
> +        return None
Just 1 suggestion for naming

```suggestion
class While(Stmt):
    
    test: Expr
    body: Stmt

    def __init__(
        self,
        test: Expr,
        body: Stmt,
    ):
        self.test = while_test
        self.body = while_body

    def __call__(self, environment: Environment):
        while self.test(environment):
            self.body(environment)
        return None
```

2022-03-20 14:14 UTC, GangstersPairOfDice commented on src/pychart/__init__.py
> +__version__ = '0.6.9'
Thank you.

2022-03-20 14:15 UTC, GangstersPairOfDice commented on src/pychart/_interpreter/pyparser.py
> +        # thassa bout it
Completely forgot about this hahahaha

2022-03-20 14:19 UTC, GangstersPairOfDice reviewed
Removed phd from py.parser comments

2022-03-21 21:23 UTC, GangstersPairOfDice commented
Could someone verify the break statement please>

2022-03-21 23:09 UTC, miningape requested changes
Just changes for readability 

Do you also want to add continue? maybe a group decision

2022-03-21 23:09 UTC, miningape commented on src/pychart/_interpreter/statement.py
> +
For readability and better error messages for the user

```suggestion
class BreakStatementException(Exception):
    pass

class Break(Stmt):
    def __call__(self, environment: Environment):
        raise BreakStatementException("Cannot invoke 'break;' outside of a while loop")

```

2022-03-21 23:09 UTC, miningape commented on src/pychart/_interpreter/statement.py
> +            except pychBreakStatementExceptionJeffer:
See previous comment
```suggestion
            except BreakStatementException:
```

2022-03-28 11:31 UTC, spralja commented
> Just changes for readability
> 
> Do you also want to add `continue`? maybe a group decision

ditto on `continue` one of the most underappreciated statements.

2022-05-13 21:59 UTC, miningape approved these changes

2022-05-13 22:08 UTC, merged